import { describe, expect, it, vi } from "vitest";
import { createGoogleHttpClient, GoogleProviderError } from "./google-http";
const json = (body: unknown, status = 200) => new Response(JSON.stringify(body), { status, headers: { "content-type": "application/json" } });
describe("Google HTTP client", () => {
  it("refreshes server-side and retries exactly one authenticated 401", async () => { const fetcher = vi.fn().mockResolvedValueOnce(json({ access_token: "one" })).mockResolvedValueOnce(json({}, 401)).mockResolvedValueOnce(json({ access_token: "two" })).mockResolvedValueOnce(json({ rows: [] })); const request = createGoogleHttpClient({ clientId: "id", clientSecret: "secret", readRefreshToken: async () => "refresh", fetcher }); expect(await request("https://www.googleapis.com/test")).toEqual({ rows: [] }); expect(fetcher).toHaveBeenCalledTimes(4); });
  it.each([[429, "rate-limited"], [500, "upstream"]] as const)("does not tightly retry status %i", async (status, kind) => { const fetcher = vi.fn().mockResolvedValueOnce(json({ access_token: "token" })).mockResolvedValueOnce(json({ error: {} }, status)); const request = createGoogleHttpClient({ clientId: "id", clientSecret: "secret", readRefreshToken: async () => "refresh", fetcher }); await expect(request("https://www.googleapis.com/test")).rejects.toMatchObject({ kind }); expect(fetcher).toHaveBeenCalledTimes(2); });
  it("retains a safe HTTP status for provider diagnostics", async () => {
    const fetcher = vi.fn().mockResolvedValueOnce(json({ access_token: "token" })).mockResolvedValueOnce(json({ error: { message: "private upstream detail" } }, 400));
    const request = createGoogleHttpClient({ clientId: "id", clientSecret: "secret", readRefreshToken: async () => "refresh", fetcher });
    await expect(request("https://www.googleapis.com/test")).rejects.toMatchObject({ kind: "invalid-response", status: 400 });
  });
  it("rejects unexpected origins and malformed or oversized bodies", async () => { const request = createGoogleHttpClient({ clientId: "id", clientSecret: "secret", readRefreshToken: async () => "refresh", fetcher: vi.fn() }); await expect(request("https://evil.example/test")).rejects.toBeInstanceOf(GoogleProviderError); const fetcher = vi.fn().mockResolvedValueOnce(json({ access_token: "token" })).mockResolvedValueOnce(new Response("not json")); await expect(createGoogleHttpClient({ clientId: "id", clientSecret: "secret", readRefreshToken: async () => "refresh", fetcher })("https://www.googleapis.com/test")).rejects.toMatchObject({ kind: "invalid-response" }); });
  it("allows the official AdSense Management API origin", async () => { const fetcher = vi.fn().mockResolvedValueOnce(json({ access_token: "token" })).mockResolvedValueOnce(json({ accounts: [] })); const request = createGoogleHttpClient({ clientId: "id", clientSecret: "secret", readRefreshToken: async () => "refresh", fetcher }); await expect(request("https://adsense.googleapis.com/v2/accounts?pageSize=100")).resolves.toEqual({ accounts: [] }); });
});
