import { describe, expect, it } from "vitest";
import { transformSearchReports } from "./search-console";
const row = (keys: string[], clicks = 5) => ({ keys, clicks, impressions: 100, ctr: .05, position: 8 });
const fixture = () => ({ summary: { rows: [row([])] }, trend: { rows: [row(["2026-10-04"])] }, queries: { rows: [row(["omnilede"])] }, pages: { rows: [row(["https://omnilede.example/story"])] }, previousPages: { rows: [row(["https://omnilede.example/story"], 9)] }, countries: { rows: [row(["gbr"])] }, devices: { rows: [row(["MOBILE"])] }, sitemaps: { sitemap: [{ path: "https://omnilede.example/sitemap.xml", lastSubmitted: "2026-10-04T10:00:00Z", isPending: false, warnings: "0", errors: "0" }] }, inspections: [{ url: "https://omnilede.example/story", response: { inspectionResult: { inspectionUrl: "https://omnilede.example/story", indexStatusResult: { verdict: "PASS", coverageState: "Submitted and indexed", userCanonical: "https://omnilede.example/story", googleCanonical: "https://omnilede.example/story" } } } }] });
describe("Search Console transforms", () => {
  it("parses official-shaped performance, sitemap and inspection data", () => expect(transformSearchReports(fixture(), "https://omnilede.example")).toMatchObject({ summary: { clicks: 5 }, pages: [{ previousClicks: 9 }], sitemaps: [{ errors: 0 }], inspections: [{ verdict: "PASS" }] }));
  it("accepts a summary row when Google omits the empty keys field", () => {
    const input = fixture();
    delete (input.summary.rows[0] as { keys?: unknown }).keys;
    expect(transformSearchReports(input, "https://omnilede.example").summary).toEqual({ clicks: 5, impressions: 100, ctr: .05, position: 8 });
  });
  it("rejects missing dimensions, nonfinite metrics, foreign pages and canonicals", () => { const missing = fixture(); missing.queries = { rows: [row([])] }; expect(() => transformSearchReports(missing, "https://omnilede.example")).toThrow(/dimension/); const nan = fixture(); nan.summary = { rows: [{ ...row([]), clicks: Number.NaN }] }; expect(() => transformSearchReports(nan, "https://omnilede.example")).toThrow(/clicks/); const foreign = fixture(); foreign.pages = { rows: [row(["https://evil.example/story"])] }; expect(() => transformSearchReports(foreign, "https://omnilede.example")).toThrow(/origin/); const canonical = fixture(); canonical.inspections[0]!.response.inspectionResult.indexStatusResult.googleCanonical = "https://evil.example/story"; expect(() => transformSearchReports(canonical, "https://omnilede.example")).toThrow(/origin/); });
  it("rejects invalid or duplicate trend dates and unknown inspection enum values", () => { const invalidDate = fixture(); invalidDate.trend = { rows: [row(["2026-02-31"])] }; expect(() => transformSearchReports(invalidDate, "https://omnilede.example")).toThrow(/date/i); const duplicate = fixture(); duplicate.trend = { rows: [row(["2026-10-04"]), row(["2026-10-04"])] }; expect(() => transformSearchReports(duplicate, "https://omnilede.example")).toThrow(/duplicate/i); const verdict = fixture(); verdict.inspections[0]!.response.inspectionResult.indexStatusResult.verdict = "MYSTERY"; expect(() => transformSearchReports(verdict, "https://omnilede.example")).toThrow(/verdict/i); const indexing = fixture(); Object.assign(indexing.inspections[0]!.response.inspectionResult.indexStatusResult, { indexingState: "MYSTERY" }); expect(() => transformSearchReports(indexing, "https://omnilede.example")).toThrow(/indexingState/); });
});
